#==============================================
# 官方 Golang 1.26.1 镜像（固定版本）
#==============================================
FROM golang:1.26.1 AS builder

# 国内加速环境
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct
ENV GOSUMDB=off
ENV CGO_ENABLED=1

# 阿里云 Debian 源
RUN sed -i 's|deb.debian.org|mirrors.aliyun.com|g' /etc/apt/sources.list.d/debian.sources && \
    sed -i 's|security.debian.org|mirrors.aliyun.com|g' /etc/apt/sources.list.d/debian.sources

# 安装交叉编译器 + upx
# RUN apt update && apt install -y --no-install-recommends \
#     gcc-mingw-w64-x86-64 upx && \
#     rm -rf /var/lib/apt/lists/*

# 安装 Protobuf Go 插件
# RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
ENV PATH="/go/bin:$PATH"

WORKDIR /app

# ======================
# 测试阶段
# ======================
FROM builder AS tester

# COPY . .
COPY ./ipkg/pufo ./ipkg/pufo
# COPY ./cmd/pufo ./cmd/pufo

# 初始化模块
RUN [ -f go.mod ] || go mod init github.com/ymc-github/apkm
RUN go mod tidy

# 测试子模块（和你原版完全一致）
# RUN go test -v ./ipkg/pufo/...

RUN go test -v ./ipkg/pufo
# RUN go test -bench=. -benchmem

CMD ["sleep", "infinity"]

# ======================
# 开发阶段
# ======================
FROM builder AS dev

CMD ["/bin/sh"]